/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class FluidStackApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, FluidStackApiTimeoutError.prototype);
    }
}
