/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FluidStackApi from "../../../../api/index";
import * as core from "../../../../core";
import { ListInstanceResponse } from "../../../types/ListInstanceResponse";

export const Response: core.serialization.Schema<
    serializers.instances.list.Response.Raw,
    FluidStackApi.ListInstanceResponse[]
> = core.serialization.list(ListInstanceResponse);

export declare namespace Response {
    type Raw = ListInstanceResponse.Raw[];
}
