/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../index";

export interface ConfigurationResponse {
    /** The GPU type of the configuration. */
    gpuType: FluidStackApi.GpuType;
    /** The number of GPUs in the configuration. */
    gpuCounts: number[];
    /** The price per GPU hour of the configuration. */
    pricePerGpuHr: string;
    estimatedProvisioningTimeMinutes?: number;
    /** The regions the configuration is available in. */
    regions: FluidStackApi.Region[];
}
