/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GpuModelResponse {
    /** The FluidStack name of the GPU model */
    name: string;
    /** Memory capacity of the GPU in megabytes */
    memorySizeMb?: number;
}
