/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../index";

export interface HttpValidationError {
    detail?: FluidStackApi.ValidationError[];
}
