/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InstanceStatus = "running" | "pending" | "unhealthy" | "terminated" | "stopped";

export const InstanceStatus = {
    Running: "running",
    Pending: "pending",
    Unhealthy: "unhealthy",
    Terminated: "terminated",
    Stopped: "stopped",
} as const;
