/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InstanceStatus =
    | "running"
    | "pending"
    | "unhealthy"
    | "shutting_down"
    | "terminated"
    | "stopping"
    | "stopped";

export const InstanceStatus = {
    Running: "running",
    Pending: "pending",
    Unhealthy: "unhealthy",
    ShuttingDown: "shutting_down",
    Terminated: "terminated",
    Stopping: "stopping",
    Stopped: "stopped",
} as const;
