/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InstanceStatus = "running" | "starting" | "pending" | "failed" | "terminated" | "stopped" | "stopping";

export const InstanceStatus = {
    Running: "running",
    Starting: "starting",
    Pending: "pending",
    Failed: "failed",
    Terminated: "terminated",
    Stopped: "stopped",
    Stopping: "stopping",
} as const;
