/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../index";

export interface ListInstanceResponse {
    /** The unique identifier of the instance */
    id: string;
    /** The current status of the instance */
    status?: FluidStackApi.InstanceStatus;
    /**
     * The username used to connect to the instance
     *
     * For example, to connect to the instance via SSH, use; "ssh <username>@<ip_address> -p <ssh_port>".
     */
    username?: string;
    /** The SSH port used to connect to the instance */
    sshPort?: string;
    /** A list of the SSH key names that can be used for logging into the instance with an SSH client */
    sshKeys?: string[];
    /** The IP address of the instance */
    ipAddress?: string;
    /** The name provided when the instance was created */
    name?: string;
    /** The current hourly price of the instance per processor based on its current status */
    currentRate?: number;
    /** The configuration used to create the instance */
    configuration?: FluidStackApi.ConfigurationResponse;
    /** The creation date and time of the instance */
    createdAt?: Date;
}
