/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../index";

export interface ListInstanceResponse {
    /** The unique identifier of the instance. */
    id: string;
    /** The current status of the instance. */
    status?: FluidStackApi.InstanceStatus;
    /** The username used to connect to the instance. For example, to connect to the instance via SSH, use: "ssh -i <path/to/private/key> <username>@<ip_address>". */
    username?: string;
    /** The SSH port used to connect to the instance. */
    sshPort?: string;
    /** The names of the SSH keys used to login to the instance. */
    sshKeys?: string[];
    /** The IP address of the instance. */
    ipAddress?: string;
    /** The name provided when the instance was created. */
    name?: string;
    /** The current hourly price of the instance per processor based on its current status. */
    currentGpuHrCost?: number;
    /** The configuration used to create the instance. */
    configuration?: FluidStackApi.ConfigurationInstanceResponse;
    /** The creation date and time of the instance. */
    createdAt?: Date;
    /** The volumes attached to the instance. */
    volumes?: FluidStackApi.VolumeInstanceResponse[];
}
