/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../index";

export interface OperatingSystemResponse {
    /** The friendly name of the operating system */
    name: string;
    /** A description of the operating system, detailing the list of pre-installed packages and customizations, if any */
    description?: string;
    /** The unique slug identifier of the operating system */
    label: FluidStackApi.SupportedOperatingSystem;
}
