/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../index";

export interface OperatingSystemResponse {
    /** The friendly name of the operating system. */
    name: string;
    /** The description of the operating system, detailing the pre-installed packages and customisations, if any. */
    description?: string;
    /** The unique slug identifier of the operating system. */
    label: FluidStackApi.SupportedOperatingSystem;
}
