/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Region =
    | "NORWAY"
    | "CANADA"
    | "SWEDEN"
    | "NETHERLANDS"
    | "TEXAS_USA"
    | "CALIFORNIA_USA"
    | "ARIZONA_USA"
    | "VIRGINIA_USA"
    | "ILLINOIS_USA"
    | "JAPAN"
    | "UTAH_USA"
    | "WASHINGTON_USA"
    | "GERMANY"
    | "INDIA"
    | "ISRAEL";

export const Region = {
    Norway: "NORWAY",
    Canada: "CANADA",
    Sweden: "SWEDEN",
    Netherlands: "NETHERLANDS",
    TexasUsa: "TEXAS_USA",
    CaliforniaUsa: "CALIFORNIA_USA",
    ArizonaUsa: "ARIZONA_USA",
    VirginiaUsa: "VIRGINIA_USA",
    IllinoisUsa: "ILLINOIS_USA",
    Japan: "JAPAN",
    UtahUsa: "UTAH_USA",
    WashingtonUsa: "WASHINGTON_USA",
    Germany: "GERMANY",
    India: "INDIA",
    Israel: "ISRAEL",
} as const;
