/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SshKeyResponse {
    /** The name of the SSH key */
    name: string;
    /** The public key */
    publicKey?: string;
}
