/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SupportedOperatingSystem = "ubuntu_20_04_lts_nvidia" | "ubuntu_22_04_lts_nvidia";

export const SupportedOperatingSystem = {
    Ubuntu2004LtsNvidia: "ubuntu_20_04_lts_nvidia",
    Ubuntu2204LtsNvidia: "ubuntu_22_04_lts_nvidia",
} as const;
