/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SupportedOperatingSystem =
    | "ubuntu_22_04_lts"
    | "ubuntu_20_04_lts"
    | "ubuntu_20_04_lts_nvidia"
    | "ubuntu_22_04_lts_nvidia";

export const SupportedOperatingSystem = {
    Ubuntu2204Lts: "ubuntu_22_04_lts",
    Ubuntu2004Lts: "ubuntu_20_04_lts",
    Ubuntu2004LtsNvidia: "ubuntu_20_04_lts_nvidia",
    Ubuntu2204LtsNvidia: "ubuntu_22_04_lts_nvidia",
} as const;
