/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../index";

export interface ValidationError {
    loc: FluidStackApi.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
