/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../index";

export interface VolumeInstanceResponse {
    /** The ID of the volume. */
    id: FluidStackApi.EntityId;
    /** The name of the volume. */
    name: string;
    /** The size of the volume in GB. */
    sizeGb: number;
    /** The status of the volume. */
    status?: FluidStackApi.VolumeStatus;
    /** The current hourly rate of the volume. */
    costGbHr: string;
    /** The creation time of the volume. */
    createdAt?: Date;
    /** The update time of the volume. */
    updatedAt?: Date;
}
