/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VolumeStatus = "creating" | "attached" | "attaching" | "error" | "deleted";

export const VolumeStatus = {
    Creating: "creating",
    Attached: "attached",
    Attaching: "attaching",
    Error: "error",
    Deleted: "deleted",
} as const;
