/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "my_ssh_key",
 *         publicKey: "<my_public_key>"
 *     }
 */
export interface CreateSshKeyRequest {
    /** The name of the SSH key. */
    name: string;
    /** The public key of the SSH key. */
    publicKey: string;
}
