/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";
import { GpuType } from "./GpuType";
import { Region } from "./Region";

export const ConfigurationResponse: core.serialization.ObjectSchema<
    serializers.ConfigurationResponse.Raw,
    FluidStackApi.ConfigurationResponse
> = core.serialization.object({
    gpuType: core.serialization.property("gpu_type", GpuType),
    gpuCounts: core.serialization.property("gpu_counts", core.serialization.list(core.serialization.number())),
    pricePerGpuHr: core.serialization.property("price_per_gpu_hr", core.serialization.string()),
    estimatedProvisioningTimeMinutes: core.serialization.property(
        "estimated_provisioning_time_minutes",
        core.serialization.number().optional()
    ),
    regions: core.serialization.list(Region),
});

export declare namespace ConfigurationResponse {
    interface Raw {
        gpu_type: GpuType.Raw;
        gpu_counts: number[];
        price_per_gpu_hr: string;
        estimated_provisioning_time_minutes?: number | null;
        regions: Region.Raw[];
    }
}
