/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";

export const ConfigId: core.serialization.Schema<serializers.ConfigId.Raw, FluidStackApi.ConfigId> =
    core.serialization.string();

export declare namespace ConfigId {
    type Raw = string;
}
