/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";

export const GpuModelResponse: core.serialization.ObjectSchema<
    serializers.GpuModelResponse.Raw,
    FluidStackApi.GpuModelResponse
> = core.serialization.object({
    name: core.serialization.string(),
    memorySizeMb: core.serialization.property("memory_size_mb", core.serialization.number().optional()),
});

export declare namespace GpuModelResponse {
    interface Raw {
        name: string;
        memory_size_mb?: number | null;
    }
}
