/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";

export const GpuType: core.serialization.Schema<serializers.GpuType.Raw, FluidStackApi.GpuType> =
    core.serialization.enum_([
        "RTX_A4000_16GB",
        "RTX_A6000_48GB",
        "RTX_A5000_24GB",
        "A100_PCIE_80GB",
        "A40_48GB",
        "A30_24GB",
        "A100_SXM4_80GB",
        "A10_PCIE_24GB",
        "A100_SXM4_40GB",
        "A100_PCIE_40GB",
        "A100_NVLINK_80GB",
        "A100_NVLINK_40GB",
        "H100_SXM5_80GB",
        "H100_PCIE_80GB",
        "H100_NVLINK_80GB",
        "RTX_6000_ADA_48GB",
        "L40_48GB",
        "L4_24GB",
        "T4_16GB",
    ]);

export declare namespace GpuType {
    type Raw =
        | "RTX_A4000_16GB"
        | "RTX_A6000_48GB"
        | "RTX_A5000_24GB"
        | "A100_PCIE_80GB"
        | "A40_48GB"
        | "A30_24GB"
        | "A100_SXM4_80GB"
        | "A10_PCIE_24GB"
        | "A100_SXM4_40GB"
        | "A100_PCIE_40GB"
        | "A100_NVLINK_80GB"
        | "A100_NVLINK_40GB"
        | "H100_SXM5_80GB"
        | "H100_PCIE_80GB"
        | "H100_NVLINK_80GB"
        | "RTX_6000_ADA_48GB"
        | "L40_48GB"
        | "L4_24GB"
        | "T4_16GB";
}
