/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";

export const HealthCheckOutSchema: core.serialization.ObjectSchema<
    serializers.HealthCheckOutSchema.Raw,
    FluidStackApi.HealthCheckOutSchema
> = core.serialization.object({
    status: core.serialization.string().optional(),
});

export declare namespace HealthCheckOutSchema {
    interface Raw {
        status?: string | null;
    }
}
