/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";
import { InstanceStatus } from "./InstanceStatus";
import { ConfigurationInstanceResponse } from "./ConfigurationInstanceResponse";
import { VolumeInstanceResponse } from "./VolumeInstanceResponse";

export const ListInstanceResponse: core.serialization.ObjectSchema<
    serializers.ListInstanceResponse.Raw,
    FluidStackApi.ListInstanceResponse
> = core.serialization.object({
    id: core.serialization.string(),
    status: InstanceStatus.optional(),
    username: core.serialization.string().optional(),
    sshPort: core.serialization.property("ssh_port", core.serialization.string().optional()),
    sshKeys: core.serialization.property("ssh_keys", core.serialization.list(core.serialization.string()).optional()),
    ipAddress: core.serialization.property("ip_address", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
    currentGpuHrCost: core.serialization.property("current_gpu_hr_cost", core.serialization.number().optional()),
    configuration: ConfigurationInstanceResponse.optional(),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    volumes: core.serialization.list(VolumeInstanceResponse).optional(),
});

export declare namespace ListInstanceResponse {
    interface Raw {
        id: string;
        status?: InstanceStatus.Raw | null;
        username?: string | null;
        ssh_port?: string | null;
        ssh_keys?: string[] | null;
        ip_address?: string | null;
        name?: string | null;
        current_gpu_hr_cost?: number | null;
        configuration?: ConfigurationInstanceResponse.Raw | null;
        created_at?: string | null;
        volumes?: VolumeInstanceResponse.Raw[] | null;
    }
}
