/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";
import { SupportedOperatingSystem } from "./SupportedOperatingSystem";

export const OperatingSystemResponse: core.serialization.ObjectSchema<
    serializers.OperatingSystemResponse.Raw,
    FluidStackApi.OperatingSystemResponse
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    label: SupportedOperatingSystem,
});

export declare namespace OperatingSystemResponse {
    interface Raw {
        name: string;
        description?: string | null;
        label: SupportedOperatingSystem.Raw;
    }
}
