/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";

export const SshKeyResponse: core.serialization.ObjectSchema<
    serializers.SshKeyResponse.Raw,
    FluidStackApi.SshKeyResponse
> = core.serialization.object({
    name: core.serialization.string(),
    publicKey: core.serialization.property("public_key", core.serialization.string().optional()),
});

export declare namespace SshKeyResponse {
    interface Raw {
        name: string;
        public_key?: string | null;
    }
}
