/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";

export const SupportedOperatingSystem: core.serialization.Schema<
    serializers.SupportedOperatingSystem.Raw,
    FluidStackApi.SupportedOperatingSystem
> = core.serialization.enum_(["ubuntu_20_04_lts_nvidia", "ubuntu_22_04_lts_nvidia"]);

export declare namespace SupportedOperatingSystem {
    type Raw = "ubuntu_20_04_lts_nvidia" | "ubuntu_22_04_lts_nvidia";
}
