/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";

export const VolumeStatus: core.serialization.Schema<serializers.VolumeStatus.Raw, FluidStackApi.VolumeStatus> =
    core.serialization.enum_(["creating", "attached", "attaching", "error", "deleted"]);

export declare namespace VolumeStatus {
    type Raw = "creating" | "attached" | "attaching" | "error" | "deleted";
}
