/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as FluidStackApi from "../../api/index";
import * as core from "../../core";

export const VolumeInstanceResponseInputCostGbHr: core.serialization.Schema<
    serializers.VolumeInstanceResponseInputCostGbHr.Raw,
    FluidStackApi.VolumeInstanceResponseInputCostGbHr
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.string()]);

export declare namespace VolumeInstanceResponseInputCostGbHr {
    type Raw = number | string;
}
