/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../../../../index";

/**
 * @example
 *     {
 *         name: "my_instance_name",
 *         gpuType: FluidStackApi.GpuType.RtxA500024Gb,
 *         sshKey: "my_ssh_key",
 *         operatingSystemLabel: FluidStackApi.SupportedOperatingSystem.Ubuntu2004LtsNvidia
 *     }
 */
export interface CreateInstanceRequest {
    /** The custom name of the instance. */
    name?: string;
    /** The GPU type of the instance. */
    gpuType: FluidStackApi.GpuType;
    /** The number of GPUs to attach to the instance. */
    gpuCount?: number;
    /** The SSH key name to add to the instance. This SSH key is used to connect to the instance. */
    sshKey: string;
    /** The operating system label used to create the instance. */
    operatingSystemLabel?: FluidStackApi.SupportedOperatingSystem;
    /** The region in which to create the instance. */
    region?: FluidStackApi.Region;
    /** The volumes attached to the instance. */
    volumes?: FluidStackApi.VolumeInstanceResponse[];
}
