/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FluidStackApi from "../../../../index";

/**
 * @example
 *     {
 *         name: "name",
 *         gpuType: FluidStackApi.GpuType.RtxA400016Gb,
 *         sshKeys: ["<ssh_key_name>"]
 *     }
 */
export interface CreateInstanceRequest {
    /** The name of the instance */
    name: string;
    gpuType: FluidStackApi.GpuType;
    /** The number of GPUs to attach to the instance */
    gpuCount?: number;
    /**
     * The list of SSH key names to add to the instance
     *
     * These SSH keys are used to connect to the instance.
     */
    sshKeys: string[];
    /** The operating system label to be used to create the instance */
    operatingSystemLabel?: FluidStackApi.SupportedOperatingSystem;
}
