/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FluidStackApiEnvironment = {
    Default: "https://platform.fluidstack.io",
} as const;

export type FluidStackApiEnvironment = typeof FluidStackApiEnvironment.Default;
