/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FluidStackApi from "../../../../api/index";
import * as core from "../../../../core";
import { ConfigurationResponse } from "../../../types/ConfigurationResponse";

export const Response: core.serialization.Schema<
    serializers.configurations.list.Response.Raw,
    FluidStackApi.ConfigurationResponse[]
> = core.serialization.list(ConfigurationResponse);

export declare namespace Response {
    type Raw = ConfigurationResponse.Raw[];
}
